<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-01 07:02
=======
# Generated by Django 5.2.5 on 2025-10-30 15:15
>>>>>>> 9e12ccaad165a9138b31203e8b21409c15578598

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('code', models.CharField(max_length=20, unique=True)),
                ('teacher_name', models.CharField(max_length=100)),
                ('student_name', models.TextField()),
                ('midscore', models.IntegerField(blank=True, null=True)),
                ('finalscore', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField()),
=======
                ('credits', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
>>>>>>> 9e12ccaad165a9138b31203e8b21409c15578598
            ],
        ),
    ]
